<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="ChandNaz" failures="0" tests="3" name="ChandNaz.Tests.SubmitOrderTest" time="41.144" errors="1" timestamp="2023-12-29T19:31:50 IST" skipped="0">
  <testcase classname="ChandNaz.Tests.SubmitOrderTest" name="submitOrder" time="19.591"/>
  <testcase classname="ChandNaz.Tests.SubmitOrderTest" name="VerifyOrders" time="8.087">
    <error message="
Method public void ChandNaz.Tests.SubmitOrderTest.VerifyOrders(java.util.HashMap) requires a @DataProvider named : getData" type="org.testng.TestNGException">
      <![CDATA[org.testng.TestNGException: 
Method public void ChandNaz.Tests.SubmitOrderTest.VerifyOrders(java.util.HashMap) requires a @DataProvider named : getData
at org.testng.internal.Parameters.findDataProvider(Parameters.java:526)
at org.testng.internal.Parameters.handleParameters(Parameters.java:763)
at org.testng.internal.Parameters.handleParameters(Parameters.java:728)
at org.testng.internal.invokers.ParameterHandler.handleParameters(ParameterHandler.java:72)
at org.testng.internal.invokers.ParameterHandler.createParameters(ParameterHandler.java:51)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:911)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- VerifyOrders -->
  <testcase classname="ChandNaz.Tests.SubmitOrderTest" name="submitOrder" time="13.466"/>
</testsuite> <!-- ChandNaz.Tests.SubmitOrderTest -->
